/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package happy.jyc.android_dependency_analyzer

import org.gradle.api.Project
import org.gradle.api.Plugin

class AndroidDependencyAnalyzerPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.tasks.register("jycDependencySize", DependencySizeTask::class.java)
        project.tasks.register("jycAARAnalyze", AARSizeTask::class.java)
    }
}
